### ISSUE TITLE
Scripts not attached to scenes

### ISSUE THREAD

**Issue by jchen183** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#1]
Hi,

I've been trying to open up the scenes, following the instructions on the readme file, but it looks like none of the scripts were attached when they were imported. Do you know what I may be doing wrong?

**Comment by EnoxSoftware** [comment]
Are you using OpenCVForUnityUWP_Beta3.unitypackage?

**Comment by jchen183** [comment]
Yes, I am. The scripts in HoloLensWithOpenCVForUnityExample are not attached in the scenes, too. Thanks for the quick response.

**Comment by jchen183** [comment]
I was using Unity 5.4.0f3 HTP . When I tried using Unity 5.5.2f1, all the files were there but now I can't choose UWP as the target. Any ideas?

**Comment by jchen183** [comment]
I got it to work! Couple of things...
1. You may need to download the Window Store target package if you haven't done so already.
2. I got an 'OutputPath property is not set for this project' error when I tried building it in Visual Studio. I just restarted my computer and it fixed the problem.
