### ISSUE TITLE
Face recognition is not working

### ISSUE THREAD

**Issue by dzak83** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#13]
Hi,
I followed the exact steps to get the setup but I can't get the face recognition to work. All other examples are fine. The only difference might be the current version of OpenCV for Unity as I don't think I can get that older version 2.2.1.

Any ideas what to check? Example like HoloLensPhotoCaptureExample is taking picture but it doesn't select faces.

**Comment by EnoxSoftware** [comment]
Does 'haarcascade_frontalface_alt.xml' and 'lbpcascade_frontalface.xml' exist in the 'Assets/StreamingAssets/' folder?

**Comment by dzak83** [comment]
Yea, I think it was about those missing files. I also did few other changes so I can't confirm but that it's the most likely. Thanks for replying so quickly!
