### ISSUE TITLE
Unity Version

### ISSUE THREAD

**Issue by jchen183** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#14]
Hi,

I am having issues in regard to what version of Unity I should be using. When using the suggested version (Unity 2017.1.3f1), I am getting XR namespace doesn't exist errors. Apparently only Unity versions 2017.2 and after use XR and any previous version uses the VR namespace. Is there any updates as to which version of Unity we should use?

Thanks!

**Comment by EnoxSoftware** [comment]
Thank you for your inquiry.

As you said, I think that if the VR namespace error is fixed, it works with the new Unity editor version.
However,  it seems that breaking changes have been made to HoloToolKit 2017.2.1.0 running on Unity editor 2017.2.
It is necessary to modify the example scenes to make it work properly.

**Comment by jchen183** [comment]
For Unity Version 2017.1.3f1, I had an issue where Core did not have a rotate function, so I commented out the line to remove the error.

I do not know if it is related but when I build the project, I am not able to select the different demos on the menu screen. Do you know anything that would cause this?

**Comment by EnoxSoftware** [comment]
What is the version of OpenCV for Unity you are using?
This issue does not occur if the latest version of OpenCV for Unity is used

**Comment by jchen183** [comment]
I imported the most recent OpenCV for Unity available to me (2.1.3 according to the readme). The rotate issue is on the WebcamTextureToMathelper.cs file in the HololenswithOpenCVForUnityExample asset.

Assets/HoloLensWithOpenCVForUnityExample/Scripts/Utils/WebCamTextureToMatHelper.cs(504,22): error CS0117: `OpenCVForUnity.Core' does not contain a definition for `rotate'

I tried commenting out the rotate and build the file but I cannot select anything on the menu (the cursor goes thru the menu) and on the face detection demo, the screen is a bright white plane instead of a transparent frame. Not sure if these are issues related to the rotate mechanism...

**Comment by EnoxSoftware** [comment]
Environment
Windows 10 Pro 1709
Windows 10 SDK 10.0.14393.0 to 10.0.16299.0
Visual Studio 2017 (v151.5.0)
Unity 2017.1.3f1
HoloToolkit-Unity-v1.2017.1.2 (https://github.com/Microsoft/MixedRealityToolkit-Unity/releases)
OpenCV for Unity 2.2.6 (https://assetstore.unity.com/packages/tools/integration/opencv-for-unity-21088)
HoloLensCameraStream (https://github.com/VulcanTechnologies/HoloLensCameraStream)

Need to use "OpenCV for Unity" 2.2.6 or later.
