### ISSUE TITLE
The HololensArUcoExample is slow and has lacks 

### ISSUE THREAD

**Issue by uelipeter** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#17]
I tried running the HololensArUcoExample and was not very happy with my experience. It was very slow and had some lacks. When I moved the marker, the cube would move in steps. Is there a way to optimize this?

**Comment by EnoxSoftware** [comment]
Unfortunately, I can't think of any solution to this problem right away.
If you need more sophisticated quality, we recommend that you consider using the Vuforia.
https://www.vuforia.com/
