### ISSUE TITLE
Facial detection overlays not working

### ISSUE THREAD

**Issue by gerwalk** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#18]
I can build and run the samples on the HoloLens but when I run the Face Detection Overlays example and then open up images of faces on my PC monitor, I'm not getting the expected red boxes over detected faces as shown in your screenshots. I do have `haarcascade_frontalface_alt.xml` and `lbpcascade_frontalface.xml` in StreamingAssets as mentioned in #13.

**Comment by EnoxSoftware** [comment]
Does the problem occur even in the editor on PC?

**Comment by gerwalk** [comment]
This ended up being an issue with building with IL2CPP (HoloLensCameraStream works under Unity 2018.2.16) because code wrapped with `#if NETFX_CORE` wasn't being compiled. I made some workarounds and got the overlay rectangles to show up.
