### ISSUE TITLE
ArUco tracking on Hololens 2 is not accurate

### ISSUE THREAD

**Issue by mikecancelosi** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#23]
When trying to track an ArUco marker on the Hololens 2, the tracking is fairly close, but is not entirely accurate. I'm using the cameraInsrinsicsChecker scene to capture the correct CamMatrix, but it is slightly off. I'm using a 5 foot by 4 foot desk as my object, and when capturing the marker, the desk is tilted around 30 degrees. 

Is there a better way to determine the correct CamMatrix settings? Or perhaps predetermined settings for the Hololens 2

**Comment by EnoxSoftware** [comment]
Unfortunately, I haven't gotten the HoloLens 2, so I haven't tried this example.
In order for the example to work correctly, you must use the HoloLensCameraStream Asset to get accurate projectionMatrix and cameraToWorldMatrix values every frame.
I don't know if HololensCameraStream Assets is compatible with Hololens2 at this time.

**Comment by mikecancelosi** [comment]
I was mistaken. My image sizes and 3D points were slightly off.

**Comment by RenSiyao** [comment]
Is your Hololens2 enabled sensor data acquisition? Why is my Hololens2 application installed but not working?

**Comment by EnoxSoftware** [comment]
To the owner of Hololens2.
I want to know the answer to this question. #29

**Comment by mikecancelosi** [comment]
Hey sorry, but I can't help. I switched jobs and no longer have access to the hololens 2. Sorry about that. Thank you for your software
