### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vitoJackLove** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#25]
In the case of face recognition, I only have the left eye to render the picture

**Comment by vitoJackLove** [comment]
I Seting All ,but i dont  look picture in my all eye

**Comment by vitoJackLove** [comment]
My device is hololens2

**Comment by EnoxSoftware** [comment]
Unfortunately, I don't have a HoloLens2.
This example was created with the HoloLens.

Are the examples of face recognition you're trying out self-created?
Could you tell us how it works in simpler examples (e.g. ComicFilterExample)?

**Comment by vitoJackLove** [comment]
It is too laggy for me to change Stereo rendering mode to Multi Pass. I think my scene is too stuck. He stays below 30fps. The scene I use is HoloLensFaceDetectionExample. He's your official case. I haven't changed anything

**Comment by vitoJackLove** [comment]
Stereo is too laggy to switch Rendering Mode to Multi Pass. Unfortunately, my project is too long to stay below 30FPS, and it is not very fast to identify people, and the speed of recognition is still good. Is it possible to optimize

**Comment by vitoJackLove** [comment]
Stereo is too laggy to switch Rendering Mode to Multi Pass. Unfortunately, my project is too long to stay below 30FPS, and it is not very fast to identify people, and the speed of identifying pictures is still acceptable. Is it possible to optimize

**Comment by vitoJackLove** [comment]
> Unfortunately, I don't have a HoloLens2.
> This example was created with the HoloLens.
> 
> Are the examples of face recognition you're trying out self-created?
> Could you tell us how it works in simpler examples (e.g. ComicFilterExample)?

Stereo is too laggy to switch Rendering Mode to Multi Pass. Unfortunately, my project is too long to stay below 30FPS, and it is not very fast to identify people, and the speed of identifying pictures is still acceptable. Is it possible to optimize

**Comment by EnoxSoftware** [comment]
What is the specific method you are using for face recognition processing?

**Comment by vitoJackLove** [comment]
https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample/issues/25#issuecomment-636358568

**Comment by vitoJackLove** [comment]
I use the face recognition case of this project. It's a little slow and the frame rate is not high

**Comment by vitoJackLove** [comment]
Can you help me? Tell me how to solve the problem of recognition speed. He makes me very upset. I use the face recognition scene in this project. thank you

**Comment by EnoxSoftware** [comment]
The following is a typical method I used for optimization in the development of my HoloLens app.
- Use HoloLensCameraStream Asset instead of WebCamTexture of Unity API to get the camera image.
- Reduce the resolution of images passed to processing processes such as face detection, and reduce the frequency of processing.
