### ISSUE TITLE
Question: Is the pluggin compatible with Hololens 2?

### ISSUE THREAD

**Issue by mintos002** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#27]
Hi, I´m trying the ArUco scene example with the Hololens 2 and I'm unable to compile the project, so I would like to know if the sample scene is compatible with Hololens 2.

Thanks!

**Comment by EnoxSoftware** [comment]
Unfortunately, I don't have a HoloLens2.
This example was created with the HoloLens.

**Comment by mintos002** [comment]
No problem, thanks anyway! :)
