### ISSUE TITLE
ArUco Example - Head Movement inverted

### ISSUE THREAD

**Issue by egmontmayer** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#28]
I am using the HoloLensWithOpenCVForUnityExample with Unity2019.4.2 and with the newest MixedRealityToolkit 2.4.0.
I have followed the steps 1-7 closely and think it should be setup correctly, as there are no build errors.

But somehow in the ArUco example my head movement seams to be exaggerated:
https://youtu.be/vrrV-by1Fpg

If you look closely the marker in the CameraFeed seams to be correct...

P.S.
I have tried with Unity 2018.4.24f and with the MRTK 2.2.0 and there this problem does not exist.

**Comment by EnoxSoftware** [comment]
This is a strange result.
I recently tried it with Unity 2019.4.5f1 and MRTK 2.4.0 and this problem did not exist.

**Comment by egmontmayer** [comment]
Thanks for your response, yes indeed it was some inconsistencies on my side...
I had both marker size and the requested frame size setup the wrong way. 
It works now.
