### ISSUE TITLE
FPS is very low 

### ISSUE THREAD

**Issue by sevelee** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#3]
I followed the steps to set up and build the project in to hololens. It works but the fps is very low! Around 05 fps.
Is there anything wrong?

**Comment by EnoxSoftware** [comment]
Have you set project to "Release" build on VS2015?
When Debug build is set, fps will decrease.

**Comment by sevelee** [comment]
Thank you very much!
That's it!
