### ISSUE TITLE
Issue deploying to Hololens 1

### ISSUE THREAD

**Issue by cxiliu** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#34]
The example runs fine in the editor (Unity 2018.4.32), but when I build and deploy through Visual Studio 2019 (16.9.0), I get the following error: 

> RemoteCommandException: Windows cannot install package Template3D_1.0.0.0_x86__pzq3xp76mxafg because this package is not compatible with the device. The package requires OS version 10.0.18362.0 or higher on the Windows.XboxSRA device family. The device is currently running OS version 10.0.17763.1757.

My unity settings are the same as the provided screenshots, where Minimum Platform version is 10.0.10240. My Hololens is running 10.0.17763, where there is no available OS updates in Settings. Both Windows 18362 and 17763 SDK are installed in Visual Studio. 

I then tried building an empty scene only using MRTK with the same build settings, this error does not occur. 

What am I missing??

**Comment by EnoxSoftware** [comment]
Hmmm, I just tried the build and deploy in almost the same environment and settings as yours and it ended up fine. (My environment is Unity2018.4.28f1, VisualStudio16.7.2)

I don't know the cause of the error you encountered, but in my experience, deleting the Unity build output file once and starting the build again sometimes solved an error in Visual Studio deploy.

<img width="1368" alt="HoloLensWithOpenCVForUnityExample_issue34" src="https://user-images.githubusercontent.com/7920392/110443619-769dc900-80ff-11eb-9f25-57f95ca4be07.png">
