### ISSUE TITLE
Error when building for Holo Lens 1 (x86)

### ISSUE THREAD

**Issue by simonjanik** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#35]
The example runs fine in the editor (Unity 2019.4.17f1, also 2018.4.28f1), but when I build, I get the following error:

ArgumentException: The Assembly UnityEditor is referenced by OpenCVForUnityCSharpDLL ('Assets/OpenCVForUnity/org/OpenCVForUnityCSharpDLL.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <2f1c602eae0d45c293fff3e3aef759fa>:0)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <2f1c602eae0d45c293fff3e3aef759fa>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <2f1c602eae0d45c293fff3e3aef759fa>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

<img width="1422" alt="error" src="https://user-images.githubusercontent.com/43337552/116448588-93ca5a80-a859-11eb-911c-92dd47bb20e2.PNG">

I tried to build the "HoloLensArUcoExample" scene of your example. Also an empty scene could not be build because of the same error.

What am I missing?

**Comment by EnoxSoftware** [comment]
The TrialVersion of OpenCVForUnity works only with UnityEditor on Windows and mac platforms.
https://enoxsoftware.com/opencvforunity/get_asset/

**Comment by vikashsingh009** [comment]
I  am also   facing  same  issues  with  
trial  OpenCvUnity   on  window  10  and  getting  same  error
![image](https://user-images.githubusercontent.com/7962189/135721218-ac785fe3-d36e-47ed-8043-402e8f211472.png)
