### ISSUE TITLE
Using Examples on The HoloLens2

### ISSUE THREAD

**Issue by Zandt97** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#36]
A previous issue describes steps to make the examples work on the HoloLens2. This issue raises some questions for me.

When i follow the steps i get multiple errors for missing assembly references. photo capture, webcam, hololensCamerastream, gesturerecogniser, VR and VideoCapture are all unrecognised.
Unity also tried to update my API's but this failed.

To be fair i'm using the latest LTS version of unity (2020.3.6f1) and MRTK 2.6. 
Could this be causing the errors? Please advise.

Previous issue: https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample/issues/29#issuecomment-830040262

**Comment by shoukailiang** [comment]
Hi, @Zandt97 .Did you fix that ?
