### ISSUE TITLE
Red video camera icon

### ISSUE THREAD

**Issue by ephynes** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#39]
Is there any way to run this code without the annoying flashing red video camera icon in the top left corner of my FOV?

**Comment by EnoxSoftware** [comment]
I am testing the example with Hololens1 and there is no red video camera icon like this one.
This problem seems to be related to the MediaStreamType property according to camnewnham's post.
https://github.com/VulcanTechnologies/HoloLensCameraStream/pull/51#issue-219243602

**Comment by ephynes** [comment]
I set it to VideoPreview because somebody said VideoRecord is much slower. I will try VideoRecord. Thanks.
