### ISSUE TITLE
I  am also   facing  same  issues  with

### ISSUE THREAD

**Issue by vikashsingh009** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#41]
I  am also   facing  same  issues  with  
trial  OpenCvUnity   on  window  10  and  getting  same  error
![image](https://user-images.githubusercontent.com/7962189/135721218-ac785fe3-d36e-47ed-8043-402e8f211472.png)

_Originally posted by @vikashsingh009 in https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample/issues/35#issuecomment-932762962_

**Comment by EnoxSoftware** [comment]
The TrialVersion of OpenCVForUnity works only with UnityEditor on Windows and mac platforms.
https://enoxsoftware.com/opencvforunity/get_asset/
It is not possible to build executable packages.

**Comment by vikashsingh009** [comment]
I have installed unity 2020 in window os,what does that mean? supported
unity editor on windows

**Comment by EnoxSoftware** [comment]
The trial version will only work in the Game window of UnityEditor.
<img width="1244" alt="2021-10-03_19h23_05" src="https://user-images.githubusercontent.com/7920392/135749599-8367b945-4220-4390-96d1-ff9c885fb5e8.png">

**Comment by vikashsingh009** [comment]
Thanks  for clarifying,actually  i  am  using  arcamara  and  its  not  working  on playmode  of  gameobject  getting  null  pointer  exception  how  to  test  opencvunity  with ARFoundation  
![image](https://user-images.githubusercontent.com/7962189/135751354-7364cedb-332f-4337-af09-8e031dba3319.png)

this  code  refrering
https://gitlab.com/-/snippets/2041871
