### ISSUE TITLE
The type or namespace name 'CameraIntrinsics' could not be found

### ISSUE THREAD

**Issue by Demi871023** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#44]
I followed the setup in Readme.md, but the error in the picture below will always appear, unable to find 'CameraIntrinsics', I would like to ask which step may be the problem?

Environment I use:
HoloLens 2
Visual Studio 2019
Unity 2019.4.7f1
Microsoft Mixed Reality Toolkit v2.2.0
OpenCV for Unity 2.4.7

![OpenCVforUnity Issue](https://user-images.githubusercontent.com/43329497/154436411-35c2dfdf-a16a-4707-a522-b49329e37a16.png)

**Comment by EnoxSoftware** [comment]
Hi, Demi871023

I found the post by a user who encountered a similar error.
EnoxSoftware/HoloLensWithOpenCVForUnityExample#30

Unfortunately, I don't have Hololens2 at hand and haven't tried it, but this thread already has a way to make my example work with Hololens2.
EnoxSoftware/HoloLensWithOpenCVForUnityExample#29

Best regards,
Enox Software

**Comment by Greatapikachu** [comment]
俺也一样
