### ISSUE TITLE
WorldManager deprecated

### ISSUE THREAD

**Issue by Cecil16** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#45]
Hello,
I'm facing an issue with Unity 2021.2.16f1. It seems that the native UnityEngine.XR library has been deprecated.
So UnityEngine.XR.WSA.WorldManager is not recognized anymore.

For example in HololensCameraStreamToMatHelper (line 419) WorldManager raises an exception at compile time.

Is there any replacement method for this ?
Thank you for your support.

**Comment by EnoxSoftware** [comment]
Same issue?
https://github.com/EnoxSoftware/HoloLensWithOpenCVForUnityExample/issues/32
