### ISSUE TITLE
ONNX model opset version 11 Integration - Not possible with Baraccuda/ Winml --- is it possible with OpenCV

### ISSUE THREAD

**Issue by Avinash0795** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#46]
Repected People,

Is there a possiblity to integrate a custom Object Detection ONNX model opset Version 11  with OpenCv for unity and is there a possiblity for it to integrate into hololens 2? Please do help me with the Question

**Comment by EnoxSoftware** [comment]
The OpenCV Dnn module is not supported by the UWP platform of OpenCV C++, so there is no plan to be implemented by OpenCVforUnity for now.
https://github.com/opencv/opencv/blob/master/modules/dnn/CMakeLists.txt#L1-L3
https://enoxsoftware.com/opencvforunity/documentation/support-modules/
