### ISSUE TITLE
HoloLensArUcoExample as Markerless Example

### ISSUE THREAD

**Issue by JochnGst** [EnoxSoftware/HoloLensWithOpenCVForUnityExample#8]
Hi,

I'm looking for an Example like the HoloLensArUcoExample but with free picures like the Markerless example in the normal OpenCV for Unity samples.

And what is in your opinion best practice to program this tracking. I thing in each sample there use a other workfolw.

Thank you

**Comment by EnoxSoftware** [comment]
Sorry for my late reply.

I have not yet tried the Markerless AR example on Hololens, but I think it will probably work.

If you want to try out a markerless AR with better performance more easily, we recommend using the Vuforia library.
